# Generated by Django 3.0.4 on 2020-03-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidences',
            options={'verbose_name_plural': 'Incidences'},
        ),
        migrations.AlterField(
            model_name='incidences',
            name='location',
            field=models.CharField(db_column='location', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidences',
            name='name',
            field=models.CharField(db_column='name', max_length=200),
        ),
    ]
